AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  RivianGearShopScrapper:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: provided.al2
      CodeUri: ./scrapper_function.zip
      Timeout: 10
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref GearShopInventoryTable
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: !Ref GearShopInventoryTable
      Events:
        ScheduledEvent:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: rate(6 hours)
            ScheduleExpressionTimezone: UTC

  GearShopInventoryStreamNotifier:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: provided.al2
      CodeUri: ./notifier_function.zip
      Timeout: 30
      Events:
        DynamoDBStreamEvent:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt GearShopInventoryTable.StreamArn
            StartingPosition: LATEST
      Environment:
        Variables:
          SOURCE_ARN: !Sub "arn:aws:ses:${AWS::Region}:${AWS::AccountId}:identity/${CustomDomainEmailIdentity}"
          SOURCE_EMAIL: !Ref SourceEmailParameter
          REPLY_TO_ADDRESSES: !Ref ReplyToAddressesParameter
          BCC_ADDRESSES: !Ref BCCAddressesParameter
          REFERRAL_CODE: !Ref RivianReferralCode
      Policies:
        - AmazonDynamoDBReadOnlyAccess
        - SESCrudPolicy:
            IdentityName: !Ref SourceEmailParameter
        - Version: '2012-10-17'
          Statement:
            Effect: Allow
            Action:
              - 'ses:SendEmail'
              - 'ses:SendRawEmail'
            Resource: "*"
            Condition:
              StringEquals:
                ses:FromAddress: !Ref SourceEmailParameter

  GearShopInventoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: GearShopInventoryTable
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S  # String type for ProductName
        - AttributeName: DateFirstSeen
          AttributeType: S  # String type for date
      KeySchema:
        - AttributeName: Id
          KeyType: HASH  # Partition key
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
        - IndexName: DateFirstSeenIndex
          KeySchema:
            - AttributeName: DateFirstSeen
              KeyType: HASH  # Partition key for the GSI
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5

  # SESDomainIdentity:
  #   Type: AWS::SES::EmailIdentity
  #   Properties:
  #     EmailIdentity: !Ref CustomDomainEmailIdentity

  # SESSourceEmailIdentity:
  #   Type: AWS::SES::EmailIdentity
  #   Properties:
  #     EmailIdentity: !Ref SourceEmailParameter

Parameters:
  CustomDomainEmailIdentity:
    Type: String
    Description: "The verified custom domain trusted identity to use with SES"
  SourceEmailParameter:
    Type: String
    Description: "The verified email address for sending emails from with SES."
  ReplyToAddressesParameter:
    Type: String
    Description: "Comma-separated list of reply-to addresses to use."
  BCCAddressesParameter:
    Type: String
    Description: "Comma-separated list of BCC email addresses to send new gear notification emails to."
  RivianReferralCode:
    Type: String
    Description: "Rivian owner referral code."

Outputs:
  RivianGearShopScrapperArn:
    Value: !GetAtt RivianGearShopScrapper.Arn
  GearShopInventoryStreamNotifierArn:
    Value: !GetAtt GearShopInventoryStreamNotifier.Arn
